Ensure the permissions change happens early

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -10,11 +10,6 @@ fail() {
 	exit ${EXIT_CODE:-1}
 }
 
-ping_server() {
-	local URL="${1}"
-	/usr/bin/curl -L --fail -m 5 "${URL}/actuator/health" &>/dev/null
-}
-
 to_boolean() {
 	local RESULT="false"
 	case "${1,,}" in
@@ -24,118 +19,24 @@ to_boolean() {
 	return 0
 }
 
-DEFAULT_WAIT=90
-DEFAULT_URL="https://localhost:9999"
-
 [ -v DEVELOPMENT ] || DEVELOPMENT="false"
 # Sanitize to ensure proper value is consumed below
 DEVELOPMENT="$(to_boolean "${DEVELOPMENT}")"
 
-# If not specifically told otherwise, wait up to
-# 90 seconds for the config server to come back up
-[ -v CONFIG_WAIT ] || CONFIG_WAIT=${DEFAULT_WAIT}
-[ -n "${CONFIG_WAIT}" ] || CONFIG_WAIT=${DEFAULT_WAIT}
-[[ ${CONFIG_WAIT} =~ ^(0|[1-9][0-9]*)$ ]] || fail "The wait period must be a number with no leading zeros [${CONFIG_WAIT}]"
-
-[ -v CONFIG_URL ] || CONFIG_URL="${DEFAULT_URL}"
-[ -n "${CONFIG_URL}" ] || fail "The config server URL must be a non-empty string [${CONFIG_URL}]"
-
-[ -v POLL_CONFIG ] || POLL_CONFIG="true"
-POLL_CONFIG="$(to_boolean "${POLL_CONFIG}")"
-
-[ -v BASE_DIR ] || BASE_DIR="/app"
-[ -v INIT_DIR ] || INIT_DIR="${BASE_DIR}/init"
-
 #
 # Update the SSL certificate trusts
 #
-
 [ -v SSL_DIR ] || SSL_DIR="/.ssl"
-/usr/local/bin/acme-init
+acme-init
 
 #
 # In case of development mode...
 #
-/usr/local/bin/add-developer
+add-developer
 
-if ${POLL_CONFIG} ; then
-	START="$(date +%s)"
-	say "Starting the polling cycle"
-	while true ; do
-		ping_server "${CONFIG_URL}" && break
+ARKCASE="$(type -P arkcase)" || fail "The arkcase executable could not be found in the path"
 
-		say "\tConfig server is not up yet at [${CONFIG_URL}]"
-		NOW="$(date +%s)"
-		[ $(( NOW - START )) -lt ${CONFIG_WAIT} ] || fail "Timed out waiting for configserver to come up at [${CONFIG_URL}]"
-		sleep 2
-	done
-	say "Config server responded, continuing"
-else
-	say "Config server polling is disabled, continuing"
-fi
-
-if [ -v WORK_DIR ] ; then
-	[ -d "${WORK_DIR}" ] || mkdir -p "${WORK_DIR}" || fail "Failed to create the Tomcat work directory [${WORK_DIR}]"
-fi
-
-if [ -v CATALINA_TMPDIR ] ; then
-	[ -d "${CATALINA_TMPDIR}" ] || mkdir -p "${CATALINA_TMPDIR}" || fail "Failed to create the Tomcat temp directory [${CATALINA_TMPDIR}]"
-fi
-
-if [ ! -v NODE_ID ] ; then
-	[ -v POD_NAME ] || POD_NAME="$(hostname)"
-	POD_NAME="${POD_NAME%%.*}"
-	[[ "${POD_NAME}" =~ ^.*-([0-9]+)$ ]] || fail "The pod name [${POD_NAME}] doesn't match the pattern for a stateful pod (must end with a number)"
-	NODE_ID="${BASH_REMATCH[1]}"
-else
-	[[ "${NODE_ID}" =~ ^[1-9][0-9]*$ ]] || fail "The NODE_ID value [${NODE_ID}] is not a valid number"
-	[ ${NODE_ID} -gt 0 ] && [ ${NODE_ID} -lt 256 ] || fail "The NODE_ID value must be in the range [1..255]"
-fi
-
-# Remove al leading zeros, just in case...
-export NODE_ID="$(( 10#${NODE_ID} ))"
-
-#
-# Apply the changes to the server.xml template
-#
-SERVER_XML="${TOMCAT_HOME}/conf/server.xml.tpl"
-if [ -f "${SERVER_XML}" ] ; then
-	TARGET="${SERVER_XML//.tpl/}"
-	say "Editing [${TARGET}] to remove the redundant cluster member"
-	XPATH="//Cluster/Channel/Interceptor/Member[@className = 'org.apache.catalina.tribes.membership.StaticMember' and starts-with(@host, '$(hostname).')]"
-	/usr/bin/xmlstarlet ed -P -d "${XPATH}" "${SERVER_XML}" > "${TARGET}"
-fi
-
-MAX_BOOT_DELAY="60"
-if [ -v BOOT_DELAY ] && [[ "${BOOT_DELAY}" =~ ^[0-9]+$ ]] ; then
-	BOOT_DELAY="$(( 10#${BOOT_DELAY} ))"
-	if [ ${BOOT_DELAY} -gt 0 ] ; then
-		[ ${BOOT_DELAY} -gt ${MAX_BOOT_DELAY} ] && BOOT_DELAY=${MAX_BOOT_DELAY}
-		say "Applying a boot delay of ${BOOT_DELAY} seconds"
-		START="$(date +%s)"
-		while true ; do
-			DIFF="$(( $(date +%s) - START ))"
-			[ ${DIFF} -ge ${BOOT_DELAY} ] && break
-			sleep 1 || fail "Boot delay aborted - exiting"
-		done
-	fi
-fi
-
-say "Launching the main process"
-
-# Add the ability to modify the environment
-[ -v ENV_FILE ] || ENV_FILE="/.env"
-[ -s "${ENV_FILE}" ] && . "${ENV_FILE}"
-
-# TODO: Re-enable this when we're on Java 11, Java 8 seems to SIGSEGV
-# when this is properly set
-# Make sure the library path includes the tomcat dir
-# [ -v LD_LIBRARY_PATH ] || LD_LIBRARY_PATH=""
-# LD_LIBRARY_PATH="${TOMCAT_HOME}/lib:${LD_LIBRARY_PATH}"
-
-[ ${#} -gt 0 ] || set -- "run"
-CATALINA="${TOMCAT_HOME}/bin/catalina.sh"
-CMD=("${CATALINA}" "${@}")
+CMD=("${ARKCASE}" "${@}")
 say "Launching as: ${CMD[@]@Q}"
 
 # If development mode is not active, just launch!
