Added support for a boot delay for clustering

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -93,6 +93,21 @@ fi
 # Remove al leading zeros, just in case...
 export NODE_ID="$(( 10#${NODE_ID} ))"
 
+MAX_BOOT_DELAY="60"
+if [ -v BOOT_DELAY ] && [[ "${BOOT_DELAY}" =~ ^[0-9]+$ ]] ; then
+	BOOT_DELAY="$(( 10#${BOOT_DELAY} ))"
+	if [ ${BOOT_DELAY} -gt 0 ] ; then
+		[ ${BOOT_DELAY} -gt ${MAX_BOOT_DELAY} ] && BOOT_DELAY=${MAX_BOOT_DELAY}
+		say "Applying a boot delay of ${BOOT_DELAY} seconds"
+		START="$(date +%s)"
+		while true ; do
+			DIFF="$(( $(date +%s) - START ))"
+			[ ${DIFF} -ge ${BOOT_DELAY} ] && break
+			sleep 1 || fail "Boot delay aborted - exiting"
+		done
+	fi
+fi
+
 say "Launching the main process"
 
 [ ${#} -gt 0 ] || set -- "run"
